### ISSUE TITLE
竞技战斗过程中，出现this.skill.getLevelData  undifined 错误。

### ISSUE THREAD

**Issue by peisy** [sgtcloud/sgtcloud-ossgame-project-zero#227]
解决不了啊！也是偶发异常，如果在普通关卡战役中 释放了技能，有很大概率在竞技场中会出现这个错误。

**Comment by highkay** [comment]
1.这个角色没有主动技能可以释放，返回了undefined
2.技能数据配置错误，类型为主动技能，但是没有配置duration这个属性

感觉1的可能性更大一些。

**Comment by highkay** [comment]
我又重现了一次，看了一下日志，似乎是挑战胜利之后重新初始化或者加载skill造成的？

同步服务器时间：1459673562992
preStage:2
curStage:3
nextStage:4
stage:2/5
创建挑战成功，ID:e2abe8ca6800431bb3df926fb7620d47
上传存档：true,内容为null
同步服务器时间：1459673572993
挑战胜利
preStage:2
curStage:3
nextStage:4
stage:2/5
Uncaught TypeError: this.skill.getLevelData is not a function
  cc.Class.extend.ctor  
  Class 
  (anonymous function)  
  listener  
  cc.eventManager._onListenerCallback  
  cc.eventManager._dispatchEventToListeners 
  cc.eventManager.dispatchEvent 
  customEventHelper.sendEvent  
  HeroUnit.extend.onMove  
  CCSUnit.extend.update 
  BattleUnit.extend.update  
  (anonymous function)  
  (anonymous function)  
  cc.Scheduler.cc.Class.extend.update  
  cc.Director.cc.Class.extend.drawScene 
  cc.DisplayLinkDirector.cc.Director.extend.mainLoop  
  callback  
挑战成功
Object
object
同步服务器时间：1459673582995
同步服务器时间：1459673592994
