### ISSUE TITLE
竞技场每天初始化挑战次数

### ISSUE THREAD

**Issue by Domineer-Long** [sgtcloud/sgtcloud-ossgame-project-zero#229]
现在的挑战次数每天并没有初始化为设定的5
现在分为两种情况
1、剩余次数小于5
2、剩余次数大于5

小于5可以直接初始化为5
大于5可以分为两种
1、当日5次用完，又购买了超过5次
2、当日5次没用，又购买了一些

**Comment by highkay** [comment]
这个为啥是question？已经close了吗？
