### ISSUE TITLE
发起一个竞技场挑战报错

### ISSUE THREAD

**Issue by highkay** [sgtcloud/sgtcloud-ossgame-project-zero#233]
看上去是本地的存档未上传？问题是这个角色已经挑战过很多次了……
估计是服务器的问题？读写并发造成的？

stage:8/8
同步服务器时间：1459674753969
上传存档：true,内容为null
同步服务器时间：1459674763962
创建挑战成功，ID:570cf457d53b4998a805b0ec5d9f104c
当前用户没有存档
上传存档：true,内容为null
同步服务器时间：1459674773969
同步服务器时间：1459674784007

**Comment by peisy** [comment]
当前用户没有存档  这是  当前角色通过后台请存档造成的。正常操作是不会造成的。
