### ISSUE TITLE
签到之后报错

### ISSUE THREAD

**Issue by Domineer-Long** [sgtcloud/sgtcloud-ossgame-project-zero#294]
![image](https://cloud.githubusercontent.com/assets/2107434/14773462/ddc9b8b2-0adc-11e6-9f0b-5e7b9ccea95d.png)

**Comment by peisy** [comment]
已修复，由于签到后会延后关闭面板，而这个时候点击跳过按钮，touch落在了 面板外，也会触发关闭签到面板，所以增加了对parent判断。
![image](https://cloud.githubusercontent.com/assets/14172495/14782191/456efbac-0b1a-11e6-8dec-dff7fb43639a.png)
